title: Carolina Mattsson
logo: /assets/img/carolina-mattsson.jpeg
description: PhD Candidate studying network scince and complexity economics.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
