title: "Carolina Mattsson"
image: /assets/img/carolina-website.jpg
description: "PhD Candidate, Network Science"
theme: jekyll-theme-minimal
pagelist:
  -
    title: Research
    url: pages/research.html
  -
    title: Leadership
    url: pages/leadership.html
  -
    title: Teaching
    url: pages/teaching.html
email: "mailto:mattsson.c@northeastern.edu"
paper: /assets/files/Mattsson_JMP.pdf
cv: /assets/files/Mattsson_CV.pdf
